# Generated by Django 4.2.3 on 2023-08-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255)),
                ('code', models.CharField(default='AD01', max_length=10, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('FEMME', 'Femme'), ('HOMME', 'Homme')], max_length=10)),
                ('tel', models.CharField(blank=True, max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/avatars')),
                ('addres', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, max_length=255)),
                ('edited_by', models.CharField(blank=True, max_length=255)),
                ('date_modification', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('etat', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ecommerce_api.user',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('RESPO', 'Respo'), ('MASTER', 'Master'), ('SUPERADMIN', 'Superadmin')], default='ADMIN', max_length=10)),
                ('etat', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ecommerce_api.user',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('etat', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ecommerce_api.user',),
        ),
    ]
